# Generated by Django 5.0.4 on 2024-04-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptchecker', '0004_useractivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserM',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('number_of_doc', models.IntegerField(default=0)),
            ],
        ),
    ]
