# Generated by Django 5.0.4 on 2024-04-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptchecker', '0006_usermadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=70)),
                ('msg', models.CharField(max_length=100)),
            ],
        ),
    ]
